#PBS -N 16proc_10000
#PBS -l nodes=1:ppn=16
#PBS -l walltime=5:00
#PBS -q coc-ice-multi
#PBS -o $PBS_JOBID.out
#PBS -e $PBS_JOBID.err

cd ~//CX4220_HW3
module load gcc mvapich2/2.2

make

mpirun -np 16 ./jacobi -n 10000 >> 10000_16proc.txt
mpirun -np 16 ./jacobi -n 10000 >> 10000_16proc.txt
mpirun -np 16 ./jacobi -n 10000 >> 10000_16proc.txt
mpirun -np 16 ./jacobi -n 10000 >> 10000_16proc.txt
mpirun -np 16 ./jacobi -n 10000 >> 10000_16proc.txt
