#PBS -N 64proc_10000
#PBS -l nodes=4:ppn=16
#PBS -l walltime=5:00
#PBS -q coc-ice-multi
#PBS -o $PBS_JOBID.out
#PBS -e $PBS_JOBID.err

cd ~//CX4220_HW3
module load gcc mvapich2/2.2

make

mpirun -np 64 ./jacobi -n 10000 >> 10000_64proc.txt
mpirun -np 64 ./jacobi -n 10000 >> 10000_64proc.txt
mpirun -np 64 ./jacobi -n 10000 >> 10000_64proc.txt
mpirun -np 64 ./jacobi -n 10000 >> 10000_64proc.txt
mpirun -np 64 ./jacobi -n 10000 >> 10000_64proc.txt
